# uses userhashtags.p (generated by getUserHashtags) (or other user-hashtag mapping) to get total hashtag counts
import cPickle as pickle
import operator

upik = pickle.load(open('userhashtags.p', 'rb'))
htcnt = {}
for user in upik:
	for hashtag in upik[user]:
		hashtag = hashtag.lower()
		if hashtag not in htcnt:
			htcnt[hashtag] = 0
		htcnt[hashtag] += 1



print sorted(htcnt.items(), key=operator.itemgetter(1), reverse=True)[:20]